# Generated by Django 5.1.2 on 2025-01-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('contactNumber', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
